//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinCustom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinCustom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; MajorGeeks.Com
        ///; How to Add Color and Appearance to Control Panel in Windows
        ///; Tutorial: https://www.majorgeeks.com/content/page/how_to_add_color_and_appearance_to_control_panel_in_windows.html
        ///
        ///[HKEY_CLASSES_ROOT\CLSID\{106ee807-9e5d-451b-a9c5-74908630cefb}]
        ///@=&quot;Color and Appearance&quot;
        ///&quot;InfoTip&quot;=&quot;Change the color of your taskbar, window borders, and Start menu&quot;
        ///&quot;System.ApplicationName&quot;=&quot;Microsoft.Personalization&quot;
        ///&quot;System.ControlPanel.Category&quot;=dword:00000001
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string add_appearance_color {
            get {
                return ResourceManager.GetString("add_appearance_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appearance {
            get {
                object obj = ResourceManager.GetObject("appearance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap context {
            get {
                object obj = ResourceManager.GetObject("context", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///;Show Copy as Path always in the right-click menu, without pressing SHIFT
        ///;Ramesh Srinivasan, Winhelponline.com
        ///
        ///[HKEY_CLASSES_ROOT\Allfilesystemobjects\shell\windows.copyaspath]
        ///@=&quot;Copy &amp;as path&quot;
        ///&quot;Icon&quot;=&quot;imageres.dll,-5302&quot;
        ///&quot;InvokeCommandOnSelection&quot;=dword:00000001
        ///&quot;VerbHandler&quot;=&quot;{f3d06e7c-1e45-4a26-847e-f9fcdee59be0}&quot;
        ///&quot;VerbName&quot;=&quot;copyaspath&quot;
        ///.
        /// </summary>
        internal static string CopyAsPath {
            get {
                return ResourceManager.GetString("CopyAsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///;Undo file to remove &quot;Copy as Path&quot; which you added earlier.
        ///;Ramesh Srinivasan, Winhelponline.com
        ///
        ///[-HKEY_CLASSES_ROOT\Allfilesystemobjects\shell\windows.copyaspath]
        ///.
        /// </summary>
        internal static string CopyAsPath_Restore {
            get {
                return ResourceManager.GetString("CopyAsPath_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cortana {
            get {
                object obj = ResourceManager.GetObject("cortana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search]
        ///&quot;AllowCortana&quot;=dword:00000000.
        /// </summary>
        internal static string disable_cortana {
            get {
                return ResourceManager.GetString("disable_cortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search]
        ///&quot;AllowCortana&quot;=dword:00000001.
        /// </summary>
        internal static string enable_cortana {
            get {
                return ResourceManager.GetString("enable_cortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next_button {
            get {
                object obj = ResourceManager.GetObject("next-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next_button_hover {
            get {
                object obj = ResourceManager.GetObject("next-button-hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next_button_hover1 {
            get {
                object obj = ResourceManager.GetObject("next_button_hover1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next_button1 {
            get {
                object obj = ResourceManager.GetObject("next_button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; MajorGeeks.Com
        ///; How to Add Color and Appearance to Control Panel in Windows
        ///; Tutorial: https://www.majorgeeks.com/content/page/how_to_add_color_and_appearance_to_control_panel_in_windows.html
        ///
        ///[-HKEY_CLASSES_ROOT\CLSID\{106ee807-9e5d-451b-a9c5-74908630cefb}]
        ///
        ///[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{106ee807-9e5d-451b-a9c5-74908630cefb}].
        /// </summary>
        internal static string remove_appearance_color {
            get {
                return ResourceManager.GetString("remove_appearance_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
